name: Java App and MySQL DB Deployment Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.4.0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Package Java App
        run: mvn clean install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: SuperheroKea
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'target/*.jar'

  execute-sql:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: success()

    steps:
      - name: Check if SQL files have been modified
        id: check-sql-files
        run: |
          SQL_FILES=$(git diff --name-only HEAD HEAD~ | grep "\.sql$")
          if [[ -z "$SQL_FILES" ]]; then
            echo "No SQL files found."
          else
            echo "SQL files found: $SQL_FILES"
            echo "::set-output name=sql-files::$SQL_FILES"
          fi
      - name: Execute SQL files against Azure Database for MySQL
        if: steps.check-sql-files.outputs.sql-files != ''
        env:
          MYSQL_SERVER_NAME: superherokea
          MYSQL_DATABASE_NAME: SuperheroDB
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          for file in ${GITHUB_WORKSPACE}/${{ steps.check-sql-files.outputs.sql-files }}; do
            mysql -h $MYSQL_SERVER_NAME -u $MYSQL_USERNAME -p$MYSQL_PASSWORD $MYSQL_DATABASE_NAME < $file
          done
